# Generated by Django 4.2 on 2023-05-03 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("hospital", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="patientdischargedetails",
            name="admitDate",
        ),
        migrations.RemoveField(
            model_name="patientdischargedetails",
            name="releaseDate",
        ),
    ]
