# Generated by Django 4.2 on 2023-05-01 21:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("doctors", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="doctorprofile",
            old_name="deparment",
            new_name="department",
        ),
    ]
