# Generated by Django 4.2 on 2023-05-09 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("doctors", "0002_rename_deparment_doctorprofile_department"),
    ]

    operations = [
        migrations.AlterField(
            model_name="department",
            name="name",
            field=models.CharField(max_length=80, unique=True),
        ),
    ]
